// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Royex.Persistance.Context;

#nullable disable

namespace Royex.Presentation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231126085609_Intialize_DataBase_and_Seed_Data_1.1")]
    partial class Intialize_DataBase_and_Seed_Data_11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Royex.Domain.Entity.GeneralManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("GeneralManager");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JoiningDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerId = 1,
                            Name = "Abir",
                            Position = 1,
                            Salary = 200
                        },
                        new
                        {
                            Id = 2,
                            JoiningDate = new DateTime(2022, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerId = 1,
                            Name = "Saddam",
                            Position = 1,
                            Salary = 200
                        },
                        new
                        {
                            Id = 3,
                            JoiningDate = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManagerId = 1,
                            Name = "Osman",
                            Position = 1,
                            Salary = 200
                        });
                });

            modelBuilder.Entity("Royex.Domain.Entity.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Manager");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JoiningDate = new DateTime(1999, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sojib",
                            Position = 0,
                            Salary = 500
                        });
                });

            modelBuilder.Entity("Royex.Domain.Entity.OfficeExecutive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GeneralManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneralManagerId");

                    b.ToTable("OfficeExecutives");
                });

            modelBuilder.Entity("Royex.Domain.Entity.GeneralManager", b =>
                {
                    b.HasOne("Royex.Domain.Entity.Manager", "Manager")
                        .WithMany("GeneralManagers")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Royex.Domain.Entity.OfficeExecutive", b =>
                {
                    b.HasOne("Royex.Domain.Entity.GeneralManager", "GeneralManager")
                        .WithMany("OfficeExecutives")
                        .HasForeignKey("GeneralManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralManager");
                });

            modelBuilder.Entity("Royex.Domain.Entity.GeneralManager", b =>
                {
                    b.Navigation("OfficeExecutives");
                });

            modelBuilder.Entity("Royex.Domain.Entity.Manager", b =>
                {
                    b.Navigation("GeneralManagers");
                });
#pragma warning restore 612, 618
        }
    }
}
