// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Royex.Persistance.Context;

#nullable disable

namespace Royex.Presentation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231127120703_AddSomeMore-data-for_seed")]
    partial class AddSomeMoredatafor_seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Royex.Domain.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBonusAdded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBonusAdded = true,
                            JoiningDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Abir",
                            Position = 0,
                            Salary = 200
                        },
                        new
                        {
                            Id = 2,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2022, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Saddam",
                            Position = 1,
                            Salary = 200
                        },
                        new
                        {
                            Id = 3,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2010, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Osman",
                            Position = 1,
                            Salary = 200
                        },
                        new
                        {
                            Id = 4,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sohel",
                            Position = 2,
                            Salary = 100
                        },
                        new
                        {
                            Id = 5,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kawser",
                            Position = 2,
                            Salary = 200
                        },
                        new
                        {
                            Id = 6,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2020, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Azad",
                            Position = 2,
                            Salary = 200
                        },
                        new
                        {
                            Id = 7,
                            IsBonusAdded = true,
                            JoiningDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tom",
                            Position = 1,
                            Salary = 200
                        },
                        new
                        {
                            Id = 8,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2023, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asik",
                            Position = 2,
                            Salary = 100
                        },
                        new
                        {
                            Id = 9,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2011, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asad",
                            Position = 1,
                            Salary = 100
                        },
                        new
                        {
                            Id = 10,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2019, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Haskil",
                            Position = 2,
                            Salary = 100
                        },
                        new
                        {
                            Id = 11,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2000, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Comok",
                            Position = 1,
                            Salary = 200
                        },
                        new
                        {
                            Id = 12,
                            IsBonusAdded = false,
                            JoiningDate = new DateTime(2015, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mijan",
                            Position = 2,
                            Salary = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
